name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check documentation
        run: python3 tools/check_docs.py
      - name: Check whitespace
        run: git diff-tree --check --root HEAD
